### ISSUE TITLE
larger than 2 GB single-part uploads

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/s3proxy#1]
jclouds dependency on Java 6 limits S3Proxy to 2 GB single-part uploads.  When jclouds merges jclouds/jclouds#426 S3Proxy can support larger uploads, although many providers have a 5 GB single-part limit.

**Comment by pstrzelczak** [comment]
I tried to upload > 2GB object into s3proxy 1.4.0 launched within a docker container obtained from https://hub.docker.com/r/stevemayne/s3proxy/ but the upload failed with: "Reason: content length must be non-negative, was: -2093729376"

I checked s3proxy code and it seems that https://issues.apache.org/jira/browse/JCLOUDS-264 is not the only problem.

Another problem is that in S3ProxyHandler.handlePutBlob() Content-Length provided in a request was parsed but not used to build PayloadBlobBuilder until cea4a42922da3ed45ab56a31e844ff9358b725f2.
Instead HttpServletRequest.getContentLength() was used that returns and int and leads to overflow.
I checked that there is HttpServletRequest.getContentLengthLong() that can possibly be used instead of parsing Content-Length header by hand.

Anyways, 1.4.0 is unusable for for >2GB single-part uploads.

**Comment by andrewgaul** [comment]
@pstrzelczak Unfortunately S3Proxy 1.4.0 still uses jclouds 1.9.x which does not include a fix for this issue.  I am still waiting on jclouds 2.0.0 release before release S3Proxy 1.5.0.  Can you try the Dockerfile from #123 instead which uses the master branch?  cea4a42922da3ed45ab56a31e844ff9358b725f2 is not relevant to your issue which only applies to v4 signatures which 1.4.0 does not support.
