### ISSUE TITLE
Docker packaging

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/s3proxy#120]
I recently discovered five projects packaging S3Proxy for Docker:

* https://github.com/bn0ir/docker-s3proxy
* https://github.com/dweinstein/dockerfile-s3proxy
* https://github.com/joshdvir/dockers/tree/master/s3proxy
* https://github.com/ritazh/s3proxydocker
* https://github.com/stevemayne/s3proxydocker

I am happy that so many people find S3Proxy useful enough to package although wonder if we can point users to a canonical version.  I added a reference to one of them in #103 although do not have enough Docker background to understand if the README should promote this instance, another, or more than one.  Or should the main S3Proxy project include a Dockerfile and publish it to Docker Hub?

@bn0ir @dweinstein @joshdvir @ritazh @stevemayne What do you think?

**Comment by bn0ir** [comment]
@andrewgaul 

Better to have Dockerfile in the main project and configure automated build on docker hub.

The image need to be as small as possible, but has enough parameters to satisfy user requirements.

That's why we want something like https://github.com/joshdvir/dockers/tree/master/s3proxy + https://github.com/ritazh/s3proxydocker + https://github.com/stevemayne/s3proxydocker

**Comment by stevemayne** [comment]
Hi Andrew, I'm happy for you to use my DockerFile as the basis for anything
you incorporate into your project.

I have looked at the other projects and they all offer differing levels of
configuration.  Ideally you want a 'complete solution' with environment
variables for all configuration options and a docker volume for any
local-data storage (so that data can be persisted).  My docker project only
supports local file system but I'd be happy to expand it to support the
other modes if you wanted to go with that.

Alternatively we could create DockerFile variants for the different storage
modes. These would be more minimal and have fewer, more specific,
configuration options.  Is this a 'bad idea' for Docker containers - do any
of you know?

Steve

**Comment by dweinstein** [comment]
+1 for official Dockerfile that is supported by the project. I'm not currently using s3proxy actively right now but having worked on the docker packaging for other projects like mitmproxy, it's much easier to setup an automated docker hub build to build releases if it's part of the project.

**Comment by ritazh** [comment]
@andrewgaul 
 
The intention for https://github.com/ritazh/s3proxydocker is to provide deployment options, guidance and samples for folks who want to test, deploy, and run S3Proxy instances next to their own applications. 

The repo provides guidance for running S3Proxy instance in a docker container and pushing S3Proxy as a containerized app in open source platforms like Dokku or Cloud Foundry so users can run and manage it next to their own applications. Alot of these are not straightforward but could be helpful for people who are using those platforms.

I think in general it would be helpful to provide deployment options and guidance for hosting S3Proxy. I'm happy to contribute these content back to this repo if you think that's a good idea.
