### ISSUE TITLE
Docker for Mac—Unable to get extended attributes

### ISSUE THREAD

**Issue by Riprock** [andrewgaul/s3proxy#155]
When using the `andrewgaul/s3proxy` image and mounting a user directory as as `/data`, I get this error when trying to read an object:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /records/yoyoyo. Reason:
<pre>    java.nio.file.FileSystemException: /data/records/yoyoyo: Unable to get list of extended attributes: Operation not supported</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

Writing the object works fine.

Docker for Mac is explicit about not supporting extended attributes in its shares. https://docs.docker.com/docker-for-mac/osxfs/#extended-attributes

**Comment by andrewgaul** [comment]
@Riprock Could you give a more complete test case?  I usually develop on Linux and cannot reproduce your symptoms on Mac OS X.  I did find some curious Unicode issues reported in #157.

**Comment by Riprock** [comment]
Hm might be tricky as Docker for Mac has its own special new volume format. Could try it with a volume driver that doesn't support extended attributes on Linux if there even is one. Or maybe make a docker-machine with a file system that doesn't support them so can't be shared.

Will look into it. 

Does s3proxy/JClouds obviously use extended attributes or is this coming from somewhere unexpected?

**Comment by andrewgaul** [comment]
@Riprock Unfortunately I lack background in Mac OS X.  I know that Docker for Linux on aufs does not support xattr although volume mounts should work.  jclouds uses xattr to store object metadata although should work around situations where the underlying file system does not support xattr.  For example people use S3Proxy on Mac OS X without Docker which silently discards object metadata, not returning errors.  Your report confuses me since S3Proxy on Docker should support this at least as well as S3Proxy without Docker.

**Comment by Riprock** [comment]
Yeah that is strange. Maybe it makes it look like xattrs are OK to begin with or something. Oh well, less guessing more reproducible cases. Will try aufs first.

**Comment by Riprock** [comment]
Linux and aufs worked fine 😕

**Comment by Riprock** [comment]
Actually I don't think that's fair.

> Data volumes are not controlled by the storage driver. Reads and writes to data volumes bypass the storage driver and operate at native host speeds.

From https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/.

Need to find a parallel where the host machine, or some sort of share on the host machine, doesn't support xattrs to test this on Linux I think.

**Comment by Riprock** [comment]
No luck. Mounting a directory on a FAT32 partition and S3Proxy works fine.

What's weird is I get this on Docker for Mac:
```
root@7fa1e8d3fa2d:/# mount | grep -o '/data type fuse.osxfs'                                              
/data type fuse.osxfs
root@7fa1e8d3fa2d:/# getfattr -d /data/tetsbucket/hey
getfattr: /data/testbucket/hey: Operation not supported
```

but on Linux Docker and a FAT32 partition for data:
```
root@d73b4543e49a:/# mount | grep -o '/data type vfat'
/data type vfat
root@d73b4543e49a:/# getfattr -d /data/testbucket/hey
root@d73b4543e49a:/#
```
No message about it not being supported, but no xattrs stored so not using them.

**Comment by smigfu** [comment]
I am facing the same issue, when trying to invoke copy-blob. Here is a stacktrace:

``3proxy_1          | W 10-12 12:58:56.416 S3Proxy-71 o.e.jetty.server.HttpChannel:396 |::] /com.XYZ.anywhere.permanent.local/d8a2db89-cc3d-fc18-b4c3-a4bc6235e93c/git/pack/28e0fed7-a5a3-d255-baf6-221bc6e2d09a.pack
s3proxy_1          | java.lang.RuntimeException: java.nio.file.FileSystemException: /var/data/com.XYZ.anywhere.permanent.local/d8a2db89-cc3d-fc18-b4c3-a4bc6235e93c/git/pack/28e0fed7-a5a3-d255-baf6-221bc6e2d09a.pack: Unable to get list of extended attributes: Operation not supported
s3proxy_1          | 	at com.google.common.base.Throwables.propagate(Throwables.java:160)
s3proxy_1          | 	at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.getBlob(FilesystemStorageStrategyImpl.java:396)
s3proxy_1          | 	at org.jclouds.blobstore.config.LocalBlobStore.loadBlob(LocalBlobStore.java:468)
s3proxy_1          | 	at org.jclouds.blobstore.config.LocalBlobStore.getBlob(LocalBlobStore.java:645)
s3proxy_1          | 	at org.jclouds.blobstore.config.LocalBlobStore.getBlob(LocalBlobStore.java:199)
s3proxy_1          | 	at org.jclouds.blobstore.config.LocalBlobStore.blobMetadata(LocalBlobStore.java:740)
s3proxy_1          | 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
s3proxy_1          | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
s3proxy_1          | 	at java.lang.reflect.Method.invoke(Method.java:606)
s3proxy_1          | 	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
s3proxy_1          | 	at com.sun.proxy.$Proxy39.blobMetadata(Unknown Source)
s3proxy_1          | 	at org.gaul.s3proxy.S3ProxyHandler.handleBlobMetadata(S3ProxyHandler.java:1324)
s3proxy_1          | 	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:555)
s3proxy_1          | 	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:260)
s3proxy_1          | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
s3proxy_1          | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
s3proxy_1          | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
s3proxy_1          | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
s3proxy_1          | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
s3proxy_1          | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
s3proxy_1          | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
s3proxy_1          | 	at java.lang.Thread.run(Thread.java:745)
s3proxy_1          | Caused by: java.nio.file.FileSystemException: /var/data/com.XYZ.anywhere.permanent.local/d8a2db89-cc3d-fc18-b4c3-a4bc6235e93c/git/pack/28e0fed7-a5a3-d255-baf6-221bc6e2d09a.pack: Unable to get list of extended attributes: Operation not supported
s3proxy_1          | 	at sun.nio.fs.LinuxUserDefinedFileAttributeView.list(LinuxUserDefinedFileAttributeView.java:119)
s3proxy_1          | 	at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.getBlob(FilesystemStorageStrategyImpl.java:349)
s3proxy_1          | 	... 20 common frames omitted`

**Comment by emanfu** [comment]
I encounter the same problem. There won't be errors if it is running directly in Mac's terminal, but when it run in a docker container in Mac, it will throw exactly the same exception ("Unable to get list of extended attributes: Operation not supported"). 

Is it possible to get this fixed?

**Comment by andrewgaul** [comment]
Unfortunately I no longer have access to a Mac so I need someone from the community to investigate this.

**Comment by andrewgaul** [comment]
Unfortunately I no longer have access to a Mac so I need someone from the community to investigate this.  You can likely work around this by using the `transient` backend instead of `filesystem`.

**Comment by geertvanheusden** [comment]
Hi @andrewgaul, I created a repository with a reproducible testcase. It also contains the stacktrace:
https://github.com/geertvanheusden/jcloud-xattr-bug

Jclouds jira ticket was created for this bug:
https://issues.apache.org/jira/browse/JCLOUDS-1218

**Comment by andrewgaul** [comment]
Some problem with the jclouds snapshot repository: https://issues.apache.org/jira/browse/JCLOUDS-1252

**Comment by andrewgaul** [comment]
Successfully pushed: https://travis-ci.org/andrewgaul/s3proxy/builds/207455891
