### ISSUE TITLE
Hystrix support

### ISSUE THREAD

**Issue by kishore25kumar** [andrewgaul/s3proxy#170]
@andrewgaul I want to encapsulate calls to backend (to azure, aws) using hystrix. Can we discuss on it further. Here is the link to hystrix https://github.com/Netflix/Hystrix. Hystrix helps in fast failover and it provides circuit breaker pattern and many more. The github link has more information about it

**Comment by andrewgaul** [comment]
Could you explain this further?  I am not familiar with Hystrix or how S3Proxy would integrate it.

**Comment by kishore25kumar** [comment]
S3proxy makes calls to multiple backends like azure aws etc.., Instead of making a direct call to the backed we wrap the calls to the backed using hystrix. Here is s3proxy case we wrap calls to jclouds library using hystrix. 
When we host s3proxy we can have fallback mechanism when the backend starts behaving un healthy (No as expected). We can have fast failovers instead of hitting the server with more number of requests etc...

**Comment by andrewgaul** [comment]
S3Proxy does few multiple RPC operations -- only multi-part upload on Azure comes to mind.  And in situations when S3Proxy does not respond, the client should retry and it would for network errors timeouts.  I do believe that any serious S3Proxy deployment would have some kind of HAProxy pointing to multiple S3Proxy instances which works since these are stateless.  And if the backend store stops responding I don't know how one would recover in some fast failover.  Usually you just set a small timeout and S3Proxy or the client should retry.

I do not want to dissuade you from this feature, but I also do not understand how it would improve the current state.

**Comment by kishore25kumar** [comment]
Here is an example scenario.
Suppose the backed starts behaving abnormal and each request is taking more time than it should be. Then the requests starts queuing up at the s3proxy side. As you said if we have a timeout the queued up requests will timeout after the specified time. After some time the queue has large number of messages to process. It takes lot of system resources and it might hang up server also. May be a server restart is required to come out of that state. Hystrix has something called circuit breaker. We can configure it such that if the requests to backend are failing or timeout, we can just open the circuit means don't give the requests to the backed instead have some fallback. Here fallback can be simple error saying service unavailable. With this there are no requests in the queuing up. Once the backend starts normal the circuit will be closed and everything will work as expected.

**Comment by kishore25kumar** [comment]
@andrewgaul any thoughts on it?

**Comment by andrewgaul** [comment]
Sorry I do not understand the need for Hystrix and this seems like a niche use case.  I do understand the need for back pressure if there clients submit too many requests since Jetty uses a thread per request.  S3Proxy could emit HTTP 503 Service Unavailable if a request cannot proceed within some user-specified timeout.  Would you like to submit a pull request for this feature?

**Comment by kishore25kumar** [comment]
@andrewgaul you are talking about pull request for hystrix or user-specified timeout? If I understood, you are asking to add a parameter called timeout and request should send 503 if they are taking more than the specified value.

**Comment by andrewgaul** [comment]
@kishore25kumar Let's track backpressure in #180 and I will gladly accept pull requests to address it.  For Hystrix I have skepticism that this has a broad use case.  You can submit a pull request and I will evaluate it but niche use cases might be best addressed by a fork.  I will accept PRs to make S3Proxy more embeddable for these kinds of non-mainline features.

**Comment by kishore25kumar** [comment]
Hystrix wiki https://github.com/Netflix/Hystrix/wiki

**Comment by kishore25kumar** [comment]
@andrewgaul Do you have any suggestions on how to make it configurable. Like as you said everyone might not need it, but if someone requires it they must be able to turn it on by using a simple flag.

**Comment by andrewgaul** [comment]
Sorry I do not have any insight into Hystrix and do not plan to investigate it.

**Comment by kishore25kumar** [comment]
@andrewgaul Any suggestions on implementing niche use case like Hystrix into s3proxy. How can we make changes to s3proxy to make these non-mainline features embeddable into s3proxy. You mentioned in previous messages you are happy to accept PRs in this regard? I am looking for some suggestions on what is the best way for this kind of things.

**Comment by andrewgaul** [comment]
Sorry I do not understand this issue.  You might try submitting a proof of concept pull request which illustrates what you want to do.
